In [2]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pycoingecko import CoinGeckoAPI
from datetime import datetime, timedelta

In [3]:
cg = CoinGeckoAPI()

# Ambil data 180 hari terakhir (6 bulan)
btc_data = cg.get_coin_market_chart_by_id(id='bitcoin', vs_currency='usd', days=180)
eth_data = cg.get_coin_market_chart_by_id(id='ethereum', vs_currency='usd', days=180)

# Ubah ke DataFrame
def to_df(coin_data):
    prices = coin_data['prices']
    df = pd.DataFrame(prices, columns=['timestamp', 'price'])
    df['Date'] = pd.to_datetime(df['timestamp'], unit='ms').dt.date
    df = df.groupby('Date').mean().reset_index()
    return df

btc_df = to_df(btc_data)
eth_df = to_df(eth_data)

# Simpan ke CSV
btc_df.to_csv("btc_data.csv", index=False)
eth_df.to_csv("eth_data.csv", index=False)

btc_df.head()

         Date     timestamp          price
0  2025-01-12  1.736640e+12   94559.551672
1  2025-01-13  1.736726e+12   94454.770896
2  2025-01-14  1.736813e+12   94456.349375
3  2025-01-15  1.736899e+12   96574.077688
4  2025-01-16  1.736986e+12  100313.152398

In [4]:
# Tentukan tanggal
end = datetime.today()
start = end - timedelta(days=180)

# Download data
tickers = ['AAPL', 'TSLA', 'NVDA']
saham_data = {}

for ticker in tickers:
    df = yf.download(ticker, start=start, end=end)
    df = df[['Close']]
    df = df.rename(columns={'Close': ticker})
    saham_data[ticker] = df

# Gabungkan semua ke 1 DataFrame
combined_stocks = pd.concat(saham_data.values(), axis=1)
combined_stocks.index = pd.to_datetime(combined_stocks.index).date
combined_stocks.reset_index(inplace=True)
combined_stocks = combined_stocks.rename(columns={'index': 'Date'})

# Simpan ke CSV
combined_stocks.to_csv("tech_stocks_data.csv", index=False)
combined_stocks.head()

C:\Users\cahya ratri lukita p\AppData\Local\Temp\ipykernel_3744\1735096131.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start=start, end=end)
[*********************100%***********************]  1 of 1 completed
C:\Users\cahya ratri lukita p\AppData\Local\Temp\ipykernel_3744\1735096131.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start=start, end=end)
[*********************100%***********************]  1 of 1 completed
C:\Users\cahya ratri lukita p\AppData\Local\Temp\ipykernel_3744\1735096131.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Price         Date        AAPL        TSLA        NVDA
Ticker                    AAPL        TSLA        NVDA
0       2025-01-13  233.835922  403.309998  133.208496
1       2025-01-14  232.718613  396.359985  131.738724
2       2025-01-15  237.297562  428.220001  136.218018
3       2025-01-16  227.710693  413.820007  133.548447
4       2025-01-17  229.426559  426.500000  137.687775

In [5]:
event_data = {
    "Date": [
        "2025-01-11", "2025-02-13", "2025-03-12",  # contoh CPI
        "2025-01-31", "2025-03-20", "2025-05-01"   # contoh FOMC
    ],
    "Event": [
        "CPI", "CPI", "CPI",
        "FOMC", "FOMC", "FOMC"
    ]
}

event_df = pd.DataFrame(event_data)
event_df["Date"] = pd.to_datetime(event_df["Date"]).dt.date
event_df.to_csv("event_dates.csv", index=False)

event_df

         Date Event
0  2025-01-11   CPI
1  2025-02-13   CPI
2  2025-03-12   CPI
3  2025-01-31  FOMC
4  2025-03-20  FOMC
5  2025-05-01  FOMC

In [6]:
# Mengecek apakah file sudah berhasil disimpan
import os

for file in ['btc_data.csv', 'eth_data.csv', 'tech_stocks_data.csv', 'event_dates.csv']:
    print(f"{file}: {'✅ Ada' if os.path.exists(file) else '❌ Tidak ditemukan'}")

btc_data.csv: ✅ Ada
eth_data.csv: ✅ Ada
tech_stocks_data.csv: ✅ Ada
event_dates.csv: ✅ Ada